routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {

    return view('welcome');

});


Route::get('country',[\App\Http\Controllers\CountryController::class,'index'])->name('indexCountry');
Route::get('country/{id}',[\App\Http\Controllers\CountryController::class,'destroy'])->name('deleteCountry');
Route::post('country-create',[\App\Http\Controllers\CountryController::class,'store'])->name('createCountry');
Route::post('country-edit',[\App\Http\Controllers\CountryController::class,'update'])->name('editCountry');




Route::resource('region', \App\Http\Controllers\RegionController::class);




Route::get('join' , function (){

//    $join = \Illuminate\Support\Facades\DB::select('
//        select r.*,c.name as country from countries c join regions r on r.country_id = c.id limit 2
//    ');

    $join = \Illuminate\Support\Facades\DB::table('regions as r')
                        ->join('countries as c','c.id','=','r.country_id')
                        ->select('r.*','c.name as country')->paginate(2);


    dd($join);


});






Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Country.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Country extends Model
{
    use HasFactory;
    public $timestamps = false;

    protected $table = 'countries';

    protected $fillable = [
        'name',
        'img'
    ];
}

app/Http/Controllers/CountryController.php
<?php

namespace App\Http\Controllers;

use App\Models\Country;
use App\Models\Message;
use GuzzleHttp\Client;
use http\Env;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use \Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Log;
use Nexmo\Laravel\Facade\Nexmo;

class CountryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {


//        $hash = Hash::make('1122');
//        $pass = '1122';
//
//        if (Hash::check($pass, $hash)){
//            dd('teng');
//        }else{
//            dd('emas');
//        }


//        $url = 'https://sms.sysdc.ru/index.php';
//        $res = Http::withToken(\Illuminate\Support\Env::get('SMS_TOKEN'))
//            ->attach('mobile_phone','998911157709')
//            ->attach('message','Salom')
//            ->post($url);

//        $url = 'myurl';
//        $user = 'ali';
//        $pass = '123';
//
//        Http::withBasicAuth($user,$pass)
//            ->post($url,[
//                'number'=>'998911157709',
//                'message'=>'Salom'
//            ]);



//        $curl = curl_init();
//
//        curl_setopt_array($curl, array(
//            CURLOPT_URL => 'https://sms.sysdc.ru/index.php',
//            CURLOPT_RETURNTRANSFER => true,
//            CURLOPT_ENCODING => '',
//            CURLOPT_MAXREDIRS => 10,
//            CURLOPT_TIMEOUT => 0,
//            CURLOPT_FOLLOWLOCATION => true,
//            CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
//            CURLOPT_CUSTOMREQUEST => 'POST',
//            CURLOPT_POSTFIELDS => array(
//                'mobile_phone' => '998991479684',
//                'message' => 'Salom Xabibullo'),
//            CURLOPT_HTTPHEADER => array(
//                'Authorization: Bearer Token'
//            ),
//        ));
//        $response = curl_exec($curl);
//
//        curl_close($curl);


//        dd($res);


        Message::message('998911157709','Model');









        $countries = Country::all();

        return view('country.index',compact('countries'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        //

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'country'=>'required'
        ]);

//        $country = Country::create([
//            'name'=>$request->country
//        ]);

        $country = new Country();
        $country->name = $request->country;
        $country->save();


        return redirect()->route('indexCountry');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request)
    {
        $country = Country::find($request->id);
        $country->name = $request->country;
        $country->update();


        return redirect()->route('indexCountry');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $country = Country::find($id);
        $country->delete();

        return redirect()->route('indexCountry');

    }
}

resources/views/country/index.blade.php
@extends('.layouts.index')


@section('main')
    <div class="container">
        <h1>Country list</h1>

        <table class="table table-striped">
            <thead>
            <tr>
                <th>N</th>
                <th>Name</th>
                <th>
                    <!-- Button trigger modal -->
                    <button type="button" class="btn btn-primary btn-sm" data-bs-toggle="modal" data-bs-target="#exampleModal">
                        Create
                    </button>

                    <!-- Modal -->
                    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLabel">Country create</h5>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                </div>
                                <form action="{{ route('createCountry')}}" method="post">
                                    @csrf
                                    @method('post')
                                    <div class="modal-body">
                                        <div class="mb-3">
                                            <label for="exampleInputEmail1" class="form-label">Country</label>
                                            <input type="text" class="form-control" name="country">
                                        </div>
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                        <input type="submit" class="btn btn-primary" value="Save changes">
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </th>
            </tr>
            </thead>
            <tbody>
            @foreach($countries as $item)
                <tr>
                    <td>{{ $loop->index+1}}</td>
                    <td><a href="{{ route('region.show',$item->id) }}">{{ $item->name }}</a></td>
                    <td>
                        <!-- Button trigger modal -->
                        <button type="button" class="btn btn-success btn-sm" data-bs-toggle="modal" data-bs-target="#exampleModal{{ $item->id }}">
                            Edit
                        </button>

                        <!-- Modal -->
                        <div class="modal fade" id="exampleModal{{ $item->id }}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="exampleModalLabel">Country Edit</h5>
                                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                    </div>
                                    <form action="{{ route('editCountry')}}" method="post">
                                        @csrf
                                        @method('post')
                                        <div class="modal-body">
                                            <div class="mb-3">
                                                <label for="exampleInputEmail1" class="form-label">Country</label>
                                                <input type="hidden" name="id" value="{{ $item->id }}">
                                                <input type="text" class="form-control" name="country" value="{{ $item->name }}">
                                            </div>
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                            <input type="submit" class="btn btn-primary" value="Save changes">
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>


                        <!-- Button trigger modal -->
                        <button type="button" class="btn btn-danger btn-sm" data-bs-toggle="modal" data-bs-target="#exampleModaldel{{ $item->id }}">
                            Delete
                        </button>

                        <!-- Modal -->
                        <div class="modal fade" id="exampleModaldel{{ $item->id }}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="exampleModalLabel">Country delete</h5>
                                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                    </div>
                                    <div class="modal-body">
                                        <div class="mb-3">

                                            <h3>Are you sure?</h3>
                                        </div>
                                    </div>

                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>

                                        <a class="btn btn-danger" href="{{ route('deleteCountry',$item->id) }}">Delete</a>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </td>

                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
@endsection