routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {

    return view('welcome');

});


Route::get('country',[\App\Http\Controllers\CountryController::class,'index'])->name('indexCountry');
Route::get('country/{id}',[\App\Http\Controllers\CountryController::class,'destroy'])->name('deleteCountry');
Route::post('country-create',[\App\Http\Controllers\CountryController::class,'store'])->name('createCountry');
Route::post('country-edit',[\App\Http\Controllers\CountryController::class,'update'])->name('editCountry');




Route::resource('region', \App\Http\Controllers\RegionController::class);




Route::get('join' , function (){

//    $join = \Illuminate\Support\Facades\DB::select('
//        select r.*,c.name as country from countries c join regions r on r.country_id = c.id limit 2
//    ');

    $join = \Illuminate\Support\Facades\DB::table('regions as r')
                        ->join('countries as c','c.id','=','r.country_id')
                        ->select('r.*','c.name as country')->paginate(2);


    dd($join);


});






Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Region.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Region extends Model
{
    use HasFactory;
    public $timestamps = false;

    protected $table = 'regions';

    protected $fillable = [
        'name',
        'country_id',
        'area',
        'img',

    ];
}

app/Http/Controllers/RegionController.php
<?php

namespace App\Http\Controllers;

use App\Models\Country;
use App\Models\Region;
use Illuminate\Http\Request;

class RegionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name'=>'required',
            'area'=>'required',
            'country_id'=>'required',
        ]);

        $region = new Region();
        $region->name = $request->name;
        $region->area = $request->area;
        $region->country_id = $request->country_id;
        $region->save();

        return redirect()->route('region.show',$request->country_id);

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $country = Country::find($id);
        $regions = Region::where('country_id','=',$id)->get();

        return view('region.index', compact('regions','country'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'name'=>'required',
            'area'=>'required',
            'img'=>'required',
        ]);

        $imageName = rand(1,1000).time().'.'.$request->file('img')->getClientOriginalExtension();

        $request->file('img')->storeAs('public/images/', $imageName);


        $region = Region::find($id);
        $region->name = $request->name;
        $region->area = $request->area;
        $region->img = $imageName;
        $region->update();

        return redirect()->route('region.show',$region->country_id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $region = Region::find($id);
        $c_id = $region->country_id;
        if (is_file(storage_path('app/public/images/'.$region->img))){
            unlink(storage_path('app/public/images/'.$region->img));
        }
        $region->delete();

        return redirect()->route('region.show',$c_id);


    }
}

resources/views/region/index.blade.php
@extends('layouts.index')


@section('main')
    <div class="container">
        <h1>
            <a href="{{ route('indexCountry') }}" class="text-decoration-none">
                <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-arrow-left-circle" viewBox="0 0 16 16">
                    <path fill-rule="evenodd" d="M1 8a7 7 0 1 0 14 0A7 7 0 0 0 1 8zm15 0A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-4.5-.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5z"/>
                </svg>
            </a>

            {{ $country->name }} Region list
        </h1>

        <table class="table table-striped">
            <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Area</th>
                <th>IMG</th>
                <th>
                    <!-- Button trigger modal -->
                    <button type="button" class="btn btn-primary btn-sm" data-bs-toggle="modal" data-bs-target="#exampleModal">
                        Create
                    </button>

                    <!-- Modal -->
                    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLabel">Region create</h5>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                </div>
                                <form action="{{ route('region.store')}}" method="post">
                                    @csrf
                                    @method('post')
                                    <div class="modal-body">
                                        <div class="mb-3">
                                            <label for="exampleInputEmail1" class="form-label">Region</label>
                                            <input type="text" class="form-control" name="name">
                                            <label for="exampleInputEmail1" class="form-label">Area</label>
                                            <input type="number" class="form-control" name="area">

                                            <input type="hidden" name="country_id" value="{{ $country->id }}">
                                        </div>
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                        <input type="submit" class="btn btn-primary" value="Save changes">
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </th>
            </tr>
            </thead>
            <tbody>
            @foreach($regions as $item)
            <tr>
                <td>{{ $item->id }}</td>
                <td>{{ $item->name }}</td>
                <td>{{ $item->area }}</td>
                <td>
                    <img src="{{ asset('public/storage/images/'.$item->img)  }}" alt="{{ $item->img }}" width="100px">
                </td>
                <td>
                    <!-- Button trigger modal -->
                    <button type="button" class="btn btn-success btn-sm" data-bs-toggle="modal" data-bs-target="#exampleModal{{ $item->id }}">
                        Edit
                    </button>

                    <!-- Modal -->
                    <div class="modal fade" id="exampleModal{{ $item->id }}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLabel">Region Edit</h5>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                </div>
                                <form action="{{ route('region.update',$item->id)}}" method="post" enctype="multipart/form-data">
                                    @csrf
                                    @method('put')
                                    <div class="modal-body">
                                        <div class="mb-3">
                                            <label for="exampleInputEmail1" class="form-label">Region</label>
                                            <input type="text" class="form-control" name="name" value="{{ $item->name }}">
                                            <label for="exampleInputEmail1" class="form-label">Area</label>
                                            <input type="number" class="form-control" name="area" value="{{ $item->area }}">
                                            <label for="exampleInputEmail1" class="form-label">Image</label>
                                            <input type="file" class="form-control" name="img" required>
                                        </div>
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                        <input type="submit" class="btn btn-primary" value="Save changes">
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>


                    <!-- Button trigger modal -->
                    <button type="button" class="btn btn-danger btn-sm" data-bs-toggle="modal" data-bs-target="#exampleModaldel{{ $item->id }}">
                        Delete
                    </button>

                    <!-- Modal -->
                    <div class="modal fade" id="exampleModaldel{{ $item->id }}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLabel">Region delete</h5>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                </div>
                                <div class="modal-body">
                                    <div class="mb-3">

                                        <h3>Are you sure?</h3>
                                    </div>
                                </div>

                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                        <form action="{{ route('region.destroy',$item->id) }}" method="post">
                                            @csrf
                                            @method('delete')

                                            <button class="btn btn-danger" type="submit">Delete</button>

                                        </form>
                                    </div>
                            </div>
                        </div>
                    </div>

                </td>

            </tr>
            @endforeach
            </tbody>
        </table>
    </div>

@endsection